In [7]:
import numpy as np

In [8]:
data = [
    [150, 7.0, 1, 'Apple'],
    [120, 6.5, 0, 'Banana'],
    [180, 7.5, 2, 'Orange'],
    [155, 7.2, 1, 'Apple'],
    [110, 6.0, 0, 'Banana'],
    [190, 7.8, 2, 'Orange'],
    [145, 7.1, 1, 'Apple'],
    [115, 6.3, 0, 'Banana']
]
data

[[150, 7.0, 1, 'Apple'],
 [120, 6.5, 0, 'Banana'],
 [180, 7.5, 2, 'Orange'],
 [155, 7.2, 1, 'Apple'],
 [110, 6.0, 0, 'Banana'],
 [190, 7.8, 2, 'Orange'],
 [145, 7.1, 1, 'Apple'],
 [115, 6.3, 0, 'Banana']]

In [23]:
# encoding 
# 'Apple' → 0
# 'Banana' → 1
# 'Orange' → 2
labels=[]
for row in data:
    i=row[3]
    labels.append(i)
  
def encode(col):
    labels1=[]
    for i in col:
        if i =='Apple':
            labels1.append(0)
        if i =='Banana':
            labels1.append(1)
        if i =='Orange':
            labels1.append(2)
    return labels1
print(encode(labels))
# we can use one-hot coding here :) in place of this 


[0, 1, 2, 0, 1, 2, 0, 1]


In [24]:
def decode(col):
    labels1=[]
    for i in col:
        if i ==0:
            labels1.append('Apple')
        if i ==1:
            labels1.append('Banana')
        if i ==2:
            labels1.append('Orange')
    return labels1

In [25]:
X_train=[row[:3] for row in data]
Y_train=encoding(labels)
X_train,Y_train


([[150, 7.0, 1],
  [120, 6.5, 0],
  [180, 7.5, 2],
  [155, 7.2, 1],
  [110, 6.0, 0],
  [190, 7.8, 2],
  [145, 7.1, 1],
  [115, 6.3, 0]],
 [0, 1, 2, 0, 1, 2, 0, 1])

In [26]:
##euclidean distance
def euclid_dist(p1,p2):
    dist=np.sqrt(np.sum((np.array(p1)-np.array(p2))**2))
    return dist

## manhattan 
def manhattan_dist(p1,p2):
    dist=(np.sum(abs(np.array(p1)-np.array(p2))))
    return dist

In [27]:
#example to test the function
a=[2,4]
b=[2,6]
print(euclid_dist(a,b))
print(manhattan_dist(a,b))

2.0
2


In [28]:
class KNN:
    def __init__(self,k=3):#stores value of k
        self.k=k
        
    def fit(self,X,y):#stores training data
        self.X_train=np.array(X)
        self.y_train=np.array(y)
        
    def predict(self,X_test):#Returns predictions for an array of test points
        d=np.array(X_test)
        predictions=[self.predict_one(x) for x in d]
        return predictions
        
    def predict_one(self,x): #Predicts the label for a single test sample
        x=np.array(x)
        dist=[] #it's an array of the distances and the labels from every point to test sample
        for i in range(len(self.X_train)):
            q=euclid_dist(x,self.X_train[i])
            dist.append((q,self.y_train[i]))
            
        dist.sort(key=lambda x:x[0]) #sorting array to find first k least distances
        
        k_nearest=dist[:self.k] #first k distances and their labels
        
        #extracting k nearest labels from k_nearest
        k_labels=[]
        for l in k_nearest:
            k_labels.append(l[1])
            
        #fing maximum repeated label in k_labels
        max_count=0
        max_label=None
        counts={}
        #we can also use Counter function for this
        for label in k_labels:
            if label not in counts:
                counts[label]=0
            counts[label]+=1
        for label in counts:
            if counts[label]>max_count:
                max_count=counts[label]
                max_label=label
                
        return max_label
        
        
    

In [29]:
model=KNN(3)
model.fit(X_train,Y_train)

In [32]:
test_data = np.array([
    [118, 6.2, 0],  # Expected: Banana
    [160, 7.3, 1],  # Expected: Apple
    [185, 7.7, 2]   # Expected: Orange
])

X_test=[row[:3] for row in test_data]
y_test=['Banana','Apple','Orange']


In [39]:
y_pred=model.predict(X_test)
y_preds=decode(y_pred)
y_preds

['Banana', 'Apple', 'Orange']

In [40]:
##bonus 
##1 accuracy checker
def accuracy_check(y_pred,y_test):
    ans=0
    for i in range(len(y_pred)):
        if y_pred[i]==y_test[i]:
            ans+=1
    return (ans/len(y_pred))*100
accuracy_check(y_preds,y_test)

100.0

In [41]:
##2 normalizing

#min-max
X=np.array(X)
X_min=X.min(axis=0)
X_max=X.max(axis=0)
X_normalized=(X-X_min)/(X_max-X_min)
print(X_normalized)
print()

#z-score
mean = X.mean(axis=0)
std = X.std(axis=0)
X_std =(X-mean)/std
print(X_std)

[[0.5        0.55555556 0.5       ]
 [0.125      0.27777778 0.        ]
 [0.875      0.83333333 1.        ]
 [0.5625     0.66666667 0.5       ]
 [0.         0.         0.        ]
 [1.         1.         1.        ]
 [0.4375     0.61111111 0.5       ]
 [0.0625     0.16666667 0.        ]]

[[ 0.15815423  0.13068205  0.16012815]
 [-0.92633194 -0.74053163 -1.12089708]
 [ 1.24264041  1.00189574  1.44115338]
 [ 0.33890193  0.47916753  0.16012815]
 [-1.28782733 -1.61174531 -1.12089708]
 [ 1.6041358   1.52462395  1.44115338]
 [-0.02259346  0.30492479  0.16012815]
 [-1.10707964 -1.0890171  -1.12089708]]


In [44]:
data

array([['120', '6.5', '0', 'Banana'],
       ['110', '6.0', '0', 'Banana'],
       ['145', '7.1', '1', 'Apple'],
       ['155', '7.2', '1', 'Apple'],
       ['190', '7.8', '2', 'Orange'],
       ['150', '7.0', '1', 'Apple'],
       ['115', '6.3', '0', 'Banana'],
       ['180', '7.5', '2', 'Orange']], dtype='<U32')

In [45]:
##3 train -test split

data=np.array(data)
np.random.shuffle(data)
#u can add seed also if u want
#now data is randomly arranged
X=[row[:3] for row in data]
y=[row[3]for row in data]
X=np.array(X)
y=np.array(y)
n=len(X)
indices=np.arange(n)

test_size=0.3
test_count = int(n* test_size)
test_indices = indices[:test_count]
train_indices = indices[test_count:]
X_train = X[train_indices]
X_test = X[test_indices]
y_train = y[train_indices]
y_test = y[test_indices]
 
X_train, X_test, y_train, y_test

(array([['155', '7.2', '1'],
        ['145', '7.1', '1'],
        ['180', '7.5', '2'],
        ['120', '6.5', '0'],
        ['150', '7.0', '1'],
        ['110', '6.0', '0']], dtype='<U32'),
 array([['115', '6.3', '0'],
        ['190', '7.8', '2']], dtype='<U32'),
 array(['Apple', 'Apple', 'Orange', 'Banana', 'Apple', 'Banana'],
       dtype='<U6'),
 array(['Banana', 'Orange'], dtype='<U6'))

In [46]:
## 4 manhattan is already implemented above